### ISSUE TITLE
don't include self in reply mentions

### ISSUE THREAD

**Issue by 33mhz** [kyo5884/enuts#2]
When replying to your own post, don't include @-mention of yourself in textarea.

Would be nice to parse all the other users mentioned in the post being replied to, into the textarea, too.

**Comment by kyo5884** [comment]
You can reply without @username by pressing shift + click reply button. 

>Would be nice to parse all the other users mentioned in the post being replied to, into the textarea, too.

I’ll make this in next update.

**Comment by kyo5884** [comment]
Fixed at v1.3.0.
